VolunteerManagementSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VolunteerManagementSystem.Models;

namespace VolunteerManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private IVolunteerRepository repository;
        public HomeController(IVolunteerRepository repo)
        {
            repository = repo;
        }
        public ActionResult Index()
        {
            return View("Index");
        }

        [HttpGet]
        public ViewResult AdminLogin()
        {
            return View();
        }
        
        public ViewResult UserLogin()
        {
            return View();
        }

        [HttpPost]
        public ViewResult AdminLogin(Login login)
        {
            foreach (var l in repository.Login)
            {
                if (login.Username == null || login.Password == null)
                {
                    return View();
                }
                else if (login.Username.Equals(l.Username) && login.Password.Equals(l.Password))
                {
                    
                    return View("AdminHome", new ViewModel { CurrentUser = login.Username });
                }
                else 
                {
                    continue;
                }
            }
            //validation
            ViewBag.ErrorMsg = "Invalid Username or Password";
            return View();
        }
        public ViewResult AdminHome(Login login)
        {
            return View(new ViewModel { Login = repository.Login, CurrentUser = login.Username });
        }
    }
}

VolunteerManagementSystem/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VolunteerManagementSystem.Models;
namespace VolunteerManagementSystem.Controllers
{
    public class VolunteerController : Controller
    {
        private IVolunteerRepository repository;
        public VolunteerController(IVolunteerRepository repo)
        {
            repository = repo;
        }
        
        public ViewResult ManageVolunteer(Login login)
        {
            return View(new ViewModel
            {
                CurrentUser = login.Username,
                Volunteers = repository.Volunteers,
                Opportunities = repository.Opportunities
            });
        }

        public ViewResult EditVolunteer(int volunteerId) =>
         View(repository.Volunteers
         .FirstOrDefault(v => v.VolunteerID == volunteerId));

        [HttpPost]
        public IActionResult EditVolunteer(Volunteer volunteer)
        {
            if (ModelState.IsValid)
            {
                repository.SaveVolunteer(volunteer);
                TempData["message"] = $"{volunteer.FirstName + ' ' + volunteer.LastName} has been saved";
                return RedirectToAction("ManageVolunteer");
            }
            else
            {
                // there is something wrong with the data values
                return View(volunteer);
            }
        }
        public ViewResult CreateVolunteer() => View("EditVolunteer", new Volunteer());
        public ViewResult ViewOpportunities()
        {
            return View(repository.Opportunities);
        }

        public ViewResult ManageOpportunity(Login login)
        {
            return View(new ViewModel
            {
                CurrentUser = login.Username,
                Volunteers = repository.Volunteers,
                Opportunities = repository.Opportunities
            });
        }

        public ViewResult EditOpportunity(int opportunityId) =>
        View(repository.Opportunities
        .FirstOrDefault(o => o.OpportunityID == opportunityId));

        [HttpPost]
        public IActionResult EditOpportunity(Opportunity opportunity)
        {
            if (ModelState.IsValid)
            {
                repository.SaveOpportunity(opportunity);
                TempData["message"] = $"{opportunity.Title} has been saved";
                return RedirectToAction("ManageOpportunity");
            }
            else
            {
                // there is something wrong with the data values
                return View(opportunity);
            }
        }
        public ViewResult CreateOpportunity() => View("EditOpportunity", new Opportunity());
        [HttpPost]
        public IActionResult Delete(int opportunityId)
        {
            Opportunity deletedOpportunity = repository.DeleteOpportunity(opportunityId);
            if (deletedOpportunity != null)
            {
                TempData["message"] = $"{deletedOpportunity.Title} was deleted";
            }
            return RedirectToAction("ManageOpportunity");
        }
        public ViewResult ViewVolunteers()
        {
            return View(new ViewModel
            {
                Volunteers = repository.Volunteers,
                Opportunities = repository.Opportunities
            });
        }

        public ViewResult SearchForm()
        {
            return View();
        }
        public ViewResult FilterForm()
        {
            return View();
        }

        public ViewResult SearchVol(SearchTerm term)
         => View("ManageVolunteer", new ViewModel
         {
             Volunteers = repository.Volunteers
            .Where(p => term.SearchString == null || p.FirstName.Contains(term.SearchString, StringComparison.CurrentCultureIgnoreCase) || p.LastName.Contains(term.SearchString, StringComparison.CurrentCultureIgnoreCase))
             .OrderBy(p => p.LastName)
         });
         
 
        public ViewResult FilterVol(FilterTerm term) => View("ManageVolunteer", new ViewModel
            {
                Volunteers = repository.Volunteers
                .Where(p => term.FilterString == null || term.FilterString.Contains(p.Approval))
                    .OrderBy(p => p.LastName)
             });
           
        public ViewResult SearchOpp(SearchTerm term)
             => View("ManageOpportunity", new ViewModel
             {
                 Opportunities = repository.Opportunities
                .Where(p => term.SearchString == null || p.Title.Contains(term.SearchString, StringComparison.CurrentCultureIgnoreCase))
                 .OrderBy(p => p.Title)
             });


         public ViewResult FilterOpp(FilterTerm term) 
            => View("ManageOpportunity", new ViewModel
            {
                Opportunities = repository.Opportunities
                    .Where(p => term.FilterString == null || term.FilterString.Contains(p.Center))
                        .OrderBy(p => p.Title)
            });

        public ViewResult MatchVol(String center)
           => View("ViewOpportunities", new ViewModel
           {
                FilterString = center,
                Opportunities = repository.Opportunities
                   .Where(o => center == null || center.Equals(o.Center))
                       .OrderBy(o => o.Title)
           });

        public ViewResult MatchOpp(String center)
           => View("ViewVolunteers", new ViewModel
           {
               FilterString = center,
               Volunteers = repository.Volunteers
                   .Where(v => center.Equals(v.CentersPreferred))
                       .OrderBy(v => v.FirstName),
           });


    }

     }
            

VolunteerManagementSystem/Views/Home/AdminHome.cshtml
@model ViewModel

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/Style/StyleSheet1.css" rel="stylesheet" type="text/css" />
</head>
<body class="center" style="background-color: powderblue">
    <h1 class="title">Hello, @Model.CurrentUser !</h1>
    <p><a class="ManageButton" asp-controller="Volunteer" asp-action="ManageVolunteer" asp-route-login="@Model.CurrentUser">Manage Volunteers</a></p>
    <p>OR</p>
    <p><a class="ManageButton" asp-controller="Volunteer" asp-action="ManageOpportunity">Manage Opportunities</a></p>
</body>
</html>

VolunteerManagementSystem/Views/Home/AdminLogin.cshtml
@model VolunteerManagementSystem.Models.Login
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/Style/StyleSheet1.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="center">
        <h1 class="title">Login</h1>
        <div style="color: red">@ViewBag.ErrorMsg</div>
        <form class="form" asp-action="AdminLogin" method="post">
            <div><span style="color:red" asp-validation-for="Username" class="text-danger"></span></div>
            <div><span style="color:red" asp-validation-for="Password" class="text-danger"></span></div>
            <div>
                <label asp-for="Username">Username: </label>
                <input class="form-control" asp-for="Username" />
            </div>
            <br />
            <div>
                <label asp-for="Password">Password: </label>
                <input class="form-control" asp-for="Password" />
            </div>
            <br />
            <div>
                <button class="button" type="submit">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>

VolunteerManagementSystem/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/Style/StyleSheet1.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="center">
        <h1 class="title">Off-The-Script VMS</h1>
        <a class="button" asp-controller="Home" asp-action="AdminLogin">Admin</a>
        <a class="button" asp-action="UserLogin">User</a>
    </div>
</body>
</html>

VolunteerManagementSystem/Views/Home/ManageOpportunity.cshtml
@model IEnumerable<VolunteerManagementSystem.Models.Login>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Manage Volunteers</title>
</head>
<body>
    <div class=" container">
        <h2>Manage Volunteers</h2>
        <input type="text" placeholder="Search...">
        <select name="Filter">
            <option value="" disabled selected>Select Filter</option>
            <option value="recent">Most Recent (60 days)</option>
            <option value="center">By Center</option>
        </select>
        <table class="table table-sm table-striped table-bordered">
            <thead>
                <tr>
                    <th>Opportunities</th>
                </tr>
            </thead>
            <tbody>
                @foreach (VolunteerManagementSystem.Models.Login r in Model)
                {
                <tr>
                    <td>@r.Username</td>
                    <td>Edit</td> <!--make this a button-->
                </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

VolunteerManagementSystem/Views/Home/ManageVolunteer.cshtml
@model IEnumerable<VolunteerManagementSystem.Models.Login>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Manage Volunteers</title>
</head>
<body>
    <div class=" container">
        <h2>Manage Volunteers</h2>
        <input type="text" placeholder="Search...">
        <select name="Filter">
            <option value="" disabled selected>Select Filter</option>
            <option value="approvedpending">Approved/Pending Approval</option>
            <option value="approved">Approved</option>
            <option value="pending">Pending Approval</option>
            <option value="disapproved">Disapproved</option>
            <option value="inactive">Inactive</option>
            <option value="all">All</option>

        </select>
        <table class="table table-sm table-striped table-bordered">
            <thead>
                <tr>
                    <th>Volunteers</th>
                </tr>
            </thead>
            <tbody>
                @foreach (VolunteerManagementSystem.Models.Login r in Model)
                {
                    <tr>
                        <td>@r.Username</td>
                        <td>Edit</td> <!--make this a button-->
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

VolunteerManagementSystem/Views/Home/UserLogin.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>User Login</title>
</head>
<body>
    <meta name="viewport" content="width=device-width" />
    <div class="text-center">
        <h1 class="display-4">User Login</h1>
    </div>
</body>
</html>